[package]
name = "async-named-locker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-future = "0.1.1"
lazy_static = "1.4.0"
log = "0.4.17"

[dev-dependencies]
async-std = "1.12.0"
